apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-pipeline

resources:
  - namespace.yaml
  - configmap.yaml
  - ingestion-service/deployment.yaml
  - indexer/deployment.yaml
  - query-api/deployment.yaml

commonLabels:
  project: log-pipeline
  managed-by: kustomize

images:
  - name: log-ingestion-service
    newTag: v1.0.0
  - name: log-indexer
    newTag: v1.0.0
  - name: query-api
    newTag: v1.0.0
